NUM_NODE=$1
NODE_RANK=$2
DEVICES=$3
MASTER_ADDR="$4"
NCCL_S_IF=$5
CODE_FILE=$6
shift 6
DEVICES_STR="$DEVICES"
let "NUM_PROC=${#DEVICES_STR}/2+1"

CUDA_VISIBLE_DEVICES=$DEVICES NCCL_DEBUG=INFO NCCL_SOCKET_IFNAME=$NCCL_S_IF NCCL_IB_DISABLE=1 NCCL_P2P_DISABLE=1 NCCL_SHM_DISABLE=1 python -m torch.distributed.launch --nnodes=$NUM_NODE --nproc_per_node=$NUM_PROC --node_rank=$NODE_RANK --master_addr=$MASTER_ADDR --master_port=1234 $CODE_FILE "$@"